### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by kietphamdev** [kietphamdev/github-course#1]
I think it looks better if the main title is a bit more orange.

```css
h1 {
  color: #f0c57c;
}
```
